name: Docker Image CI

on:
  release:
    types: [published]
    branches: [ master ]

jobs:

  admin_frontend:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/admin_frontend
          tags: latest
          tag_with_sha: true
          path: admin_frontend
          
  cart_db:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/cart_db
          tags: latest
          tag_with_sha: true
          path: cart_db
          
  cart_microservice:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/cart_microservice
          tags: latest
          tag_with_sha: true
          path: cart_microservice
          
  orders_db:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/orders_db
          tags: latest
          tag_with_sha: true
          path: orders_db
          
  orders_microservice:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/orders_microservice
          tags: latest
          tag_with_sha: true
          path: orders_microservice
          
  product_db:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/product_db
          tags: latest
          tag_with_sha: true
          path: product_db
          
  product_microservice:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/product_microservice
          tags: latest
          tag_with_sha: true
          path: product_microservice
          
  web_frontend:
    runs-on: ubuntu-latest
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: derkkila/web_frontend
          tags: latest
          tag_with_sha: true
          path: web_frontend
